Repository apimatic/core-lib-java, pull requests merged in 2022-10, with the labels that each got.

#12 feat(http-logger): move http logger from sdk to core lib
  pom.xml
  src/main/java/io/apimatic/core/configurations/http/client/HttpLogger.java
Labels: enhancement

#22 fix(oauth2-validation): add missing oauth2 validation in core lib
  README.md
  pom.xml
  src/main/java/io/apimatic/core/GlobalConfiguration.java
  src/main/java/io/apimatic/core/HttpRequest.java
  src/main/java/io/apimatic/core/authentication/HeaderAuth.java
  src/main/java/io/apimatic/core/authentication/QueryAuth.java
Labels: bug

#29 build(vulnerability-fix): upgrade jackson core and databind version
  pom.xml
  src/main/java/io/apimatic/core/utilities/CoreHelper.java
Labels: vulnerability fix

#30 build(upgrade-version-for-release): upgrade to major version
  README.md
  pom.xml
Labels: release

#37 ci(checkstyle-rules-modification): configure linter for the project
  .github/linters/checkstyle.xml
Labels: enhancement
